version: 1.1
messages:
  particle:
    enable: true
    particleType: CLOUD
    count: 4
    offsetX: 0.2
    offsetY: 0.2
    offsetZ: 0.2
  sound:
    enable: true
    soundType: BLOCK_ANVIL_STEP
    volume: 3
    pitch: 3
  settings:
    format: '%player_name% %message%'
    distance: 10
    biasY: 2.15
    visibleTextForOwner: true
    permSend: moh.send
    permSee: moh.see
    delay: 4
    sizeLine: 24
