#######################
#=MESSAGE=OVER=HEADER=#
#=========OR==========#
#===BUBBLE=MESSAGE====#
#######################
version: 1.0 #DON'T TOUCH!!!!

messages:
  particle:
    enable: true
    particleType: CLOUD #https://minecraft.fandom.com/wiki/Particles
    count: 4 #count of particle
    offsetX: 0.2 #the maximum random offset on the X axis
    offsetY: 0.2 #the maximum random offset on the X axis
    offsetZ: 0.2 #the maximum random offset on the Z axis
  sound:
    enable: true
    soundType: BLOCK_ANVIL_STEP #https://www.digminecraft.com/lists/sound_list_pc.php (block.anvil.step -> BLOCK_ANVIL_STEP)
    volume: 3 #The volume of the sound
    pitch: 3 #The pitch of the sound
  settings:
    format: '%player_name% %message%' #Supports PlaceholderAPI and HEX colors (example: &#123456)
    distance: 10
    biasY: 2.15 #height spawn of Bubble Message. The value is calculated experimentally.
    visibleTextForOwner: true
    permSend: moh.send
    permSee: moh.see
    delay: 4 #in seconds. Bubble life time